"""add ml models

Revision ID: 21cef17f515c
Revises: 294f48e587a9
Create Date: 2026-08-21 11:14:30.884226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cef17f515c'
down_revision: Union[str, Sequence[str], None] = '294f48e587a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    op.create_table('forecast_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('validation_points', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('mape', sa.Float(), nullable=False),
    sa.Column('accuracy_percent', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_accuracy_device_id'), 'forecast_accuracy', ['device_id'], unique=False)
    op.create_index(op.f('ix_forecast_accuracy_evaluated_at'), 'forecast_accuracy', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_forecast_accuracy_id'), 'forecast_accuracy', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_accuracy_organization_id'), 'forecast_accuracy', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_accuracy_organization_id'), table_name='forecast_accuracy')
    op.drop_index(op.f('ix_forecast_accuracy_id'), table_name='forecast_accuracy')
    op.drop_index(op.f('ix_forecast_accuracy_evaluated_at'), table_name='forecast_accuracy')
    op.drop_index(op.f('ix_forecast_accuracy_device_id'), table_name='forecast_accuracy')
    op.drop_table('forecast_accuracy')
    op.drop_index(op.f('ix_ml_models_id'), table_name='ml_models')
    op.drop_table('ml_models')
    # ### end Alembic commands ###
