import { BrowserRouter, Navigate, Route, Routes } from "react-router-dom";
import { AuthProvider } from "./context/AuthContext";
import ProtectedRoute from "./components/ProtectedRoute";
import Layout from "./components/layout/Layout";
import Login from "./pages/Login"; import Register from "./pages/Register"; import ForgotPassword from "./pages/ForgotPassword";
import Dashboard from "./pages/Dashboard"; import Facilities from "./pages/Facilities"; import Devices from "./pages/Devices"; import DeviceDetails from "./pages/DeviceDetails"; import Datasets from "./pages/Datasets"; import Analytics from "./pages/Analytics"; import Forecasting from "./pages/Forecasting"; import Anomalies from "./pages/Anomalies"; import RootCause from "./pages/RootCause"; import Optimization from "./pages/Optimization"; import Recommendations from "./pages/Recommendations"; import AutonomousOperations from "./pages/AutonomousOperations"; import Simulation from "./pages/Simulation"; import RealTimeMonitoring from "./pages/RealTimeMonitoring"; import Alerts from "./pages/Alerts"; import MLModels from "./pages/MLModels"; import Reports from "./pages/Reports"; import Organization from "./pages/Organization"; import Settings from "./pages/Settings";
const routes=[["/dashboard",Dashboard],["/facilities",Facilities],["/devices",Devices],["/devices/:deviceId",DeviceDetails],["/datasets",Datasets],["/analytics",Analytics],["/forecasting",Forecasting],["/anomalies",Anomalies],["/root-cause",RootCause],["/optimization",Optimization],["/recommendations",Recommendations],["/autonomous",AutonomousOperations],["/simulation",Simulation],["/real-time",RealTimeMonitoring],["/alerts",Alerts],["/ml-models",MLModels],["/reports",Reports],["/organization",Organization],["/settings",Settings]];
function Protected({ children }){ return <ProtectedRoute><Layout>{children}</Layout></ProtectedRoute>; }
export default function App(){ return <AuthProvider><BrowserRouter><Routes><Route path="/" element={<Navigate to="/dashboard" replace/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/forgot-password" element={<ForgotPassword/>}/>{routes.map(([path,Component])=><Route key={path} path={path} element={<Protected><Component/></Protected>}/>)}<Route path="*" element={<Navigate to="/dashboard" replace/>}/></Routes></BrowserRouter></AuthProvider>; }
